### ISSUE TITLE
useEffect Error

### ISSUE THREAD

**Issue by weisisheng** [JohannesKonings/fff-badminton#55]
Fairly new to React.js and getting this warning on all the pages.  

./src/views/Games/Games.js
  Line 231:6:  React Hook useEffect has a missing dependency: 'onPageRendered'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

The discussions on github and in react circles are all over the place.  Any wise guidance would be much appreciated. In the interim, digging into hooks documents.

TIA.

**Comment by JohannesKonings** [comment]
I have so far ignored the warning 😄 
The reason for this is not known to me. I will research the next days more deeply.

**Comment by weisisheng** [comment]
Thanks very much.  I will try to post here too if I find something.
